# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    working_directory: ~/bull
    docker:
      - image: circleci/elixir:1.6
        environment:
          MIX_ENV: test

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix test
      - run:
          name: Install some System dependencies
          command: sudo apt-get update -qq && sudo apt-get install -y ssh rsync
      - run:
          name: Get Mix dependencies
          command: MIX_ENV=prod mix deps.get
      - run:
          name: Compile App
          command: MIX_ENV=prod mix compile
      - run:
          name: Build App release
          command: MIX_ENV=prod mix release --env=prod;
      - deploy:
          name: Deploy to Production
          command: |
            ssh-keyscan -H $APP_HOST >> ~/.ssh/known_hosts;
            rsync -ravhz --stats --progress ./rel/$APP_NAME $APP_USER@$APP_HOST:apps;
      - deploy:
          name: Post-deploy and App restart on Production
          command: ./.circleci/post-deploy.sh
